### ISSUE TITLE
Detect Magic not working to RAW/RAI

### ISSUE THREAD

**Issue by Stonedtroll** [dev7355608/vision-5e#108]
Detect Magic in PHB 2024:

"For the duration, you sense the presence of magical effects within 30 feet of yourself. If you sense such effects, you can take the Magic action to see a faint aura around any visible creature or object in the area that bears the magic, and if an effect was created by a spell, you learn the spell’s school of magic.

The spell is blocked by 1 foot of stone, dirt, or wood; 1 inch of metal; or a thin sheet of lead."

Right now, visible or not, an aura surrounds any creature or object that is magical. 

Let me know if you need more info.

**Comment by dev7355608** [comment]
Is *"any visible creature"* supposed to mean *"any creature that does not have the Invisible condition"*? I suppose it cannot mean "visible" in the normal sense of the word, because that would be contradictory to the last paragraph (one can't see through stone, dirt, wood, metal, or lead (unless it it is transparent in some weird way)) so the might as well have omitted it.

**Comment by Stonedtroll** [comment]
I see your point but I take the last paragraph to apply to "you sense the presence of magical effects within 30 feet of yourself" and not the "you can take the Magic action to see a faint aura". Otherwise, how do you see an aura on a creature that's behind you?

**Comment by dev7355608** [comment]
I see. Just to make sure: so you read *"visible creature"* as *"a creature you can see"*?

**Comment by Stonedtroll** [comment]
I do.

**Comment by dev7355608** [comment]
Fixed in 2.5.2.

**Comment by Stonedtroll** [comment]
Brilliant! Thank you.
