### ISSUE TITLE
Ability to disable on some Token

### ISSUE THREAD

**Issue by Aiacos** [dev7355608/vision-5e#112]
Would be great to disable the Vision management on some humanoid tokens (like Thoug) or keep Basic Vision and make it working with other addon like Patrol

Thanks,
L.

**Comment by dev7355608** [comment]
I suppose the issue is that the Patrol module uses vision/sight settings of a token even if vision is not enabled on the token, and, because Vision 5e doesn't automatically configure vision on tokens with vision disabled and set every to default (0), it does not work?

**Comment by Aiacos** [comment]
Thanks a lot for you time,

I'm going to try to explain that better.

![immagine_2024-10-17_210522766](https://github.com/user-attachments/assets/f9b3dca6-5e50-4e37-aa66-5c94107275d4)

Characters with no Basic Vision (Bugbear with Darkvision in the example) works already well with token vision enabled (Vision 5e mod enabled) .
Characters with only Basic Vision (like Thug, Humans, Assasin) and Vision 5e enabled loose the Basic vision (this is usually infinite line of sight, 0 in the token) and doesn't work anymore with Patrol.

![image](https://github.com/user-attachments/assets/78458654-d9a6-4203-80b8-73b4d2401602)

It is possible to set Basic Vision for this kind of Characters within Vision5e?

Thanks,
L.

**Comment by Aiacos** [comment]
TheRipper93 author of "Patrol" have no plan to support Vision5e for now.
The only other solution would be to add back "Basic Vision" field in Vision5e, but i dont know the effort for this.

![Uploading image.png…]()

Thanks,
L.

**Comment by dev7355608** [comment]
If I added Basic Vision back, it would have the undesirable effect that all tokens would have Basic Vision by default meaning Darkvision wouldn't be grayscale unless the Vision Mode was manually switched to Darkvision. So that isn't an option considering that Vision 5e is supposed to make vision a zero configuration experience. I suppose I could make Basic Vision look exactly the same as Darkvision, but that seems a bit silly to basically have Darkvision twice as a Vision Mode just for Partol support. There's probably a better solution out there for compatibility with Partol, but I don't have the time to look into it unfortunately.

**Comment by Aiacos** [comment]
I understand, thanks for the info!
I will not stress you anymore, if you are interested feel free to implement this feature when you have time, no pressure at all!

Kind Regard,
L.
