### ISSUE TITLE
Make tokens sensed by "imprecise senses" targetable

### ISSUE THREAD

**Issue by txm3278** [dev7355608/vision-5e#18]
Currently you can't target a token that you can only hear whether you are blinded or they are invisible. They should be able to be attacked just with disadvantage (which is handled by CE/Midi)

**Comment by LukasPrism** [comment]
Oh damn, I didn't realise you couldn't – didn't even check. I thought that was one of the issues this module was aiming to solve. Folks were always complaining about being blinded and not being able to target (although of course you always could using the combat tracker). Being able to target the mystery men would be ideal for sure.

**Comment by dev7355608** [comment]
Having the token targetable may lead to information being revealed. For example, you'd be able to keep track of a token by the target pip. Also you might hear tokens through walls or underground: these tokens are not necessarily targetable/attackable. The GM needs to decide whether they can target a token that has been detected by an imprecise sense. I have a module that allows the GM to target tokens for their players: https://github.com/dev7355608/manage-player-targets. I should link it in the readme in section regarding imprecise senses.

Once targeted and/or attacked information is very likely to be revealed, because I have no control over what other modules or the system decide to show. It would need compatibility code on their end that checks whether the token imprecise and precise visible.

**Comment by LukasPrism** [comment]
Makes sense. As I mentioned players can still target via the tracker, although there at least the GM can decide if the creature is displayed or not. Thanks yeah I will grab that module!

**Comment by txm3278** [comment]
@dev7355608 I think this would be nice to have as a setting. The issues you mentioned seem avoidable without needing the dm to target for the player.

> For example, you'd be able to keep track of a token by the target pip.

Is it possible to remove the target, when the user is no longer able to sense the token? How does this currently work if a player is targeting a creature and it goes behind a wall?

> Also you might hear tokens through walls or underground: these tokens are not necessarily targetable/attackable.

With midi-qol, the attacking through a wall is already handled as it wouldn't let the attack go through.

For burrowing creatures, midi would probably need to add some compatibility to make that work

**Comment by LukasPrism** [comment]
Good points. Tposney would add that in a heartbeat. I'd still prefer the option to be able to target them – otherwise it's just extra work pinging the target for the GM to do it, or going through the tracker trying to work it out

**Comment by SiPa13** [comment]
I support having tokens targetable even if they're out of sight/invisible

**Comment by dev7355608** [comment]
https://github.com/dev7355608/vision-5e/releases/tag/v1.9.0
