### ISSUE TITLE
Option to choose creature types detected

### ISSUE THREAD

**Issue by gilfan1066** [dev7355608/vision-5e#20]
I'd like to be able to configure sense all to only include or exclude certain creature types, similar to the way Divine Sense detects only Celestials, Fiends, and Undead. One specific use case would be Blackrazor Legendary weapon from the DMG.

Blackrazor
Soul Hunter. While you hold the weapon. you are aware of the presence of Tiny or larger creatures within 60 feet of you that aren't constructs or undead.

**Comment by dev7355608** [comment]
Since description says "presence" and not "location", you'd just know that there's someone within 60 feet of you but not where. The ranger's Primeval Awareness or the basic sense of smell are other examples. These are vague senses. I'm not sure what the best way would be to communicate detection by vague senses to the user.

I very likely won't build a UI to create custom detection modes. It's not a small amount of work to get it right and expose all options. Creating new detection modes with the API is simple enough, I think; especially if you just need to copy an existing detection mode and modify it slightly.

I open to adding detection modes for all senses and abilities that exist in 5e. But there's no way to handle vague sense at the moment.
