### ISSUE TITLE
Light perception and other visions showing up as 0

### ISSUE THREAD

**Issue by ctbritt** [dev7355608/vision-5e#22]
Hi-- i just noticed this today, but whenever I'm importing creatures from a compendium, the vision isn't set correctly. For instance: 

![CleanShot 2023-07-14 at 17 34 56@2x](https://github.com/dev7355608/vision-5e/assets/4516034/912cc106-d14d-4a6c-8652-53310c320735)

that's the actor pulled from the SRD Monsters compendium, and as you can see, the light perception is set to 0 instead of ∞, and darkvision, which should be 120 is set to 0. 

The prototype token looks like this: 
![CleanShot 2023-07-14 at 17 37 09@2x](https://github.com/dev7355608/vision-5e/assets/4516034/1a102ed7-7746-4e71-8d25-4e4cfca53e31)
which seems to be correct, but the moment I import it into the world, the vision is borked. 

There are no other modules enabled except libwrapper, socketlib and Vision/Detection 5e. 

Any ideas?

**Comment by Zamrod** [comment]
To add more to this, I've been testing it. It appears to be because the Default Token configuration is being updated with these extra entries automatically:

![image](https://github.com/dev7355608/vision-5e/assets/12570777/d52b6c28-9361-44a8-b461-119ad72b144d)

What's weirder still is if you attempt to delete these entries from the default token config, they don't go away and the console says: "The specified value "Infinity" cannot be parsed, or is out of range."

**Comment by dev7355608** [comment]
Thanks for the report. I fixed the issue, but adding/removing detection modes is broken in the default token config at the moment. So you may have to reset your default token settings to clear out the incorrectly configured default detection mode. Just resetting the detection modes with the following macro should do the job as well.
```js
game.settings.set("core", DefaultTokenConfig.SETTING, mergeObject(game.settings.get("core", DefaultTokenConfig.SETTING), { "-=detectionModes": null }, { inplace: false, performDeletions: true }))
```

https://github.com/dev7355608/vision-5e/releases/tag/v1.6.3
