### ISSUE TITLE
Devil's Sight

### ISSUE THREAD

**Issue by MotoMoto1234** [dev7355608/vision-5e#30]
Devil's Sight is gray scale when it should be perfect vision.

**Comment by dev7355608** [comment]
You are correct, but the warlock should also be able the distinguish between illuminated areas and darkness in some way. That wouldn't be the case if I made it perfect, unless the light sources are animated/colored. I think it's probably more important being able to tell what is illuminated and what isn't than the ability to see colors. I didn't desaturate it a 100%, so the player should still able to tell what the colors are roughly.

Let me know what you think. I'm open to suggestions.

**Comment by LukasPrism** [comment]
Hard agree that the warlock should be able to see where darkness is. In v9 I had a toggle macro to disable my bright vision for this reason. Having bright vision 100% of the time sucks. V5E does let you toggle it off from the HUD though, so I don’t get the need for grayscale.

**Comment by MotoMoto1234** [comment]
We were toying with colorized vision but it carries over between normal and devilsight so it wouldn't be a perfect solution plus theres no way to pick your color for just devilsight.

**Comment by LukasPrism** [comment]
Hmm, is it intended that all tokens have Darkvision 0ft if they don't have the darkvision trait? It means all tokens have a HUD button that does nothing 🤔 
<img width="488" alt="Screenshot 2023-07-30 at 12 10 56 AM" src="https://github.com/dev7355608/vision-5e/assets/104886594/9a0816e2-0d0e-4eeb-b938-d585f56ac7f2">

**Comment by dev7355608** [comment]
I have to assume though that a lot of players just select devil's sight for 99% of the time, because they don't have darkvision, or because devil's sight is overall better because of the longer range and magical darkness, or just because it can be annoying to switch all the time. There are also situations where switching doesn't help: the warlock wouldn't be able to tell whether there's light behind magical darkness if devil's sight is full color, because if you switch to darkvision you won't be able to see this area at all. Vision tint is also not an option because vision effects are applied to illuminated just like they are applied to nonilluminated areas, and so the tint would make everything red. You might have noticed that even darkvision and any other desaturated vision can change the look of illuminated areas slightly. If vision was not applied to illuminated areas at all, we would have more options to create a distinct look for devil's sight in darkness, and devil's sight wouldn't affect the brightness of dim light at all.

**Comment by dev7355608** [comment]
> Hmm, is it intended that all tokens have Darkvision 0ft if they don't have the darkvision trait? It means all tokens have a HUD button that does nothing 🤔

Yes, it's necessary to be able switch back to normal sight for tokens that doesn't have darkvision. I could probably name the button something else in this case, but I wasn't sure what to call it and basically everyone has darkvision anyway and so it didn't seem too important.

**Comment by LukasPrism** [comment]
Do you mean switch back to normal vision is they have a Detection Mode like Detect Magic going?

Would it be possible to just not show the vision button at all if they only have one mode available? Unless it serves some other purpose…

**Comment by dineshm72** [comment]
Disclaimer: I am still on v10, and am only going by what I've seen in the readme and some videos I've seen in discord.

I can only report that my players will definitely, 100% complain if the devil's sight is presented as desaturated grayvision.  Source: they already do whenever the DS settings for their tokens get messed up (for me in v10,  where I occasionally have scenes they were placed in long ago where they just had DV).

I'm not sure I understand what "should also be able the distinguish between illuminated areas and darkness in some way" means.  If you mean they should be able to tell what is illuminated normally and what is darkness that they can see normally because of their devil's sight, I'm not sure I agree, that doesn't seem RAW.  As Lukas says, if they want to turn off their devil's sight, and see in whatever other vision they have, to try to understand that they have that option.  

My opinion, since you asked: if for practical reasons you want to somehow make that more evident inside of DS so players don't have to go around switching their vision back and forth, I guess I would be open to that, but not at the expense of making one of the definitely explicit parts of devil's sight not work (using darkvision desaturated coloring instead of normal coloring).  

Ideas: 
* Make the desaturation optional - we can all set it the way we prefer at our tables.
* Tone down the desaturation much more significantly to find a better happy medium.  
* Add the brightness indicators from perfect vision back in (with a keybind presumably).
* Draw faint lines where the boundaries change in the vision polygon, or something along those lines.

**Comment by dineshm72** [comment]
Though this also makes me wonder if this module has a way to handle most monster "devil's sight", which is annoyingly quite different: e.g "Devil’s Sight. Magical darkness doesn’t impede the imp’s [Darkvision]".

I guess I'm asking if there's any setting or flag that does nothing but grant the ability to pierce magical darkness with a vision sense (e.g. devil's sight for warlocks with that eldritch ability, or devil's sight for monsters with that enhancement to darkvision).

**Comment by dev7355608** [comment]
- Tweaked the appearance of devil's sight. Make sure you switch to another vision mode and back to get the new look.
- NPCs now gain devil's sight equal to their darkvision range if they have the feat.

https://github.com/dev7355608/vision-5e/releases/tag/v1.8.0

**Comment by LukasPrism** [comment]
Thanks for the speedy update! I was experimenting with the values in devils-sight.mjs and was just about to suggest what you just did... beat me to it! 👏
