### ISSUE TITLE
Vision should be grayscale while on the ethereal plane 

### ISSUE THREAD

**Issue by dev7355608** [dev7355608/vision-5e#43]

**Comment by dev7355608** [comment]
https://github.com/dev7355608/vision-5e/releases/tag/v1.10.2

**Comment by Dumbhuman** [comment]
I assume this change is to approximate vision into the Prime Material Plane from the Border Ethereal, to match the Dungeon Master's Guide description (pg. 48):

> From the Border Ethereal, a traveler can see into whatever plane it overlaps, but that plane appears muted and indistinct, its colors blurring into each other and its edges turning fuzzy. Ethereal denizens watch the plane as though peering through distorted and frosted glass, and can't see anything beyond 30 feet into the other plane.

I'm sure you don't want to dive too deeply into effects, but I think it would be a lot more distinctive from Darkvision to keep some saturation, lower the contrast, and increase the gamma.  For whatever reason (maybe old edition descriptions), I associate green with the Ethereal mists, but it's probably safer to leave that out.  Here's a little mockup I made using TokenMagicFX's Adjustment filter on a tile with baked in tokens (and one Red Mage token placed on the token layer for reasons to follow):

![image](https://github.com/dev7355608/vision-5e/assets/63615591/e6d05156-dece-4dee-9a57-ea2ccc3b56f7)

There's also an edge case which argues very strongly for needing to be able to see color regularly on the Ethereal Plane.  In the Deep Ethereal, there are Ethereal Curtains that function as portals to other planes of existence and these are associated with their destinations through distinctive colors (bright turquise, dusky gray, pale blue, reddish-brown, orange, etc.).  Of course one can't see the Material Plane from the Deep Ethereal, so it's best represented by a completely different map in which you can just turn off the Ethereal condition for all creatures involved and not worry much about vision differences other than restricting range to 30' for everyone.

Still, since seeing the color of those curtains in the Deep Ethereal is so important, I'd guess that even in the Border Ethereal that one would be able to see colors normally for creatures/objects that are also in the Border Ethereal.  It's only when viewing creatures/objects on an overlapping plane from the Border Ethereal that things are stated to look washed out (just as the range of sight from the Border Ethereal into an overlapping plane is 30 feet but the range of sight on the Border Ethereal itself is 60 feet).  

So I suppose in an ideal world things might look like this:

- Tokens with the Ethereal condition:
  - Can see tokens/tiles with the Ethereal condition up to 60 feet away and in regular color.
  - Can see tokens/tiles without the Ethereal condition up to 30 feet away and with some washed-out, mostly desaturated effect.
- Tokens without the Ethereal condition but with See Invisibility or other feature that allows seeing into the Ethereal:
  - Can see tokens/tiles with the Ethereal condition up to 60 feet away and with some washed-out, mostly desaturated effect (and probably some transparency as well as per the See Invisibility description).
