### ISSUE TITLE
[QUERY] Daylight & Darkness Detection

### ISSUE THREAD

**Issue by InstantZzz** [dev7355608/vision-5e#73]
Hello

Is Daylight and Night detection an included feature? I am unsure if I have done something incorrectly. I have the module enabled but when I set my scene to Daylight, my tokens are still unable to see until I put down an active Light Source.

I assume this doesn't work because "Daylight" is not an actual light source but purely a visual effect but I thought I'd ask to be sure.

**Comment by dev7355608** [comment]
What do you mean by "Daylight" specifically? Global Illumination or something else?

**Comment by InstantZzz** [comment]
I think so? I am talking about the "Lighting Controls" on the left-hand side of the UI. The Foundry VTT website refers to it as the "Lighting Layer controls".
![Lighting Layer Controls](https://github.com/dev7355608/vision-5e/assets/103078788/cdfbe3cc-b182-487a-83dc-abf319e8915c)

**Comment by dev7355608** [comment]
The "Daylight" button just sets the Darkness Level to 0. Darkness Level 0 doesn't mean there's light that makes token see something necessarily. For actual light you need to enable Global Illumination in daylight scenes and optionally set your Global Illumination Threshold as desired so that Global Illumination is turned off above a certain threshold if you want to use the scene in both daytime and night time. This is core Foundry behavior and not Vision 5e specific behavior.

**Comment by InstantZzz** [comment]
Okay, so it was my misunderstanding. Thank you.

**Comment by dev7355608** [comment]
Yeah, no problem. The labels of these two buttons in the Lighting Controls cause this confusion regularly.
