### ISSUE TITLE
[Feature Request] Toggle to allow downed tokens to retain vision

### ISSUE THREAD

**Issue by Skyl3lazer** [dev7355608/vision-5e#80]
My players get downed occasionally, but while unconscious they can't see anything at all. While this makes sense from a realism perspective, it would be nice to have a toggle in the options to make it so that players can still see the game when unconscious.

**Comment by dev7355608** [comment]
You could make the same argument about the blinded condition that it shouldn't take away vision: a player's token might be blinded all combat long and doesn't get to enjoy it. Or every combat might be taking place in complete darkness and a player without darkvision wouldn't be able to see anything either regardless of conditions.

I thought about this and I think the solution is Observer permission. If you give your players Observer permission of each other a blinded/unconscious/dead/... player can still enjoy the combat from the perceptive of their party members. Though I can see that having Observer permission can also enable metagaming as each players access to more information than they should. I was thinking perhaps we need something like temporary Observer permissions so that the GM can temporarily make a player a spectator while their unconscious or otherwise lost all their senses and it's unlikely that they'll regain them next round. But I'm not sure yet how exactly this would be implemented to make this easily manageable by the GM. Also not sure if with would be part of Vision 5e or a separate module.

**Comment by Skyl3lazer** [comment]
Is it possible to just have options for all 3 of those? (lighter darkvision, blinded, unconscious). Personally only the blinded/unconscious bother my players but I can understand all three.

**Comment by roth-michael** [comment]
If you'd like, dev, I could open up a PR just adding a settings toggle for unconscious affecting `_canDetect` and auto-enabling `blinded`. And perhaps also a toggle for blinded actually blinding the player.

**Comment by dev7355608** [comment]
I made a change in 2.1.0 that might work well to solve this issue:

> Now, while a player does have any owned nonhidden tokens with vision that are _defeated_ (_dead_), _petrified_, or _unconscious_ in the current scene, tokens with vision owned by other players become a source of vision for this player if they have limited permission over the token's actor. This behavior aims to prevent players from missing out on all the fun if their character dies, is knocked unconscious, or is petrified, which are all conditions that make the token not perceive anything and are likely to affect the character more than one round of combat.

Let me know if you have any thoughts on this behavior.

**Comment by roth-michael** [comment]
Sounds perfect to me - I'll get rid of my PR

**Comment by Skyl3lazer** [comment]
Does this work in DND 3.1?

**Comment by dev7355608** [comment]
Vision 5e 2.0.0+ is V12 only (and therefore dnd5e 3.2.0+).

**Comment by dev7355608** [comment]
Closing as completed.
