### ISSUE TITLE
[Feature Request] Perfect vision feature - change vision levels

### ISSUE THREAD

**Issue by Hawketotrot** [dev7355608/vision-5e#86]
I'd like to change how Darkvision light levels work similar to how it was in Perfect Vision - I would like to change the Darkvision ability to see Dim Light as Bright Light and keep it as Dim. I only want Darkness to become Dim Light and nothing more.

![Screenshot 2024-06-23 231241](https://github.com/dev7355608/vision-5e/assets/173652569/e4307f4f-e34d-4af6-b88a-40c5c8d9f1ec)

**Comment by dev7355608** [comment]
Core allows only to boost dim to bright light in the entire scene. That's what the core Darkvision vision mode does. Vision 5e changes this so that you don't see every light as bright outside of your darkvision range, but that also mean you don't see it as bright within the range. Implementing it they way Perfect Vision would be very hacky and a lot of effort, so the decision was made early that Vision 5e won't try to make darkvision behave rules-accurate in this regard.

**Comment by Hawketotrot** [comment]
> Core allows only to boost dim to bright light in the entire scene. That's what the core Darkvision vision mode does. Vision 5e changes this so that you don't see every light as bright outside of your darkvision range, but that also mean you don't see it as bright within the range. Implementing it they way Perfect Vision would be very hacky and a lot of effort, so the decision was made early that Vision 5e won't try to make darkvision behave rules-accurate in this regard.

Except thats not what your module does. I don't want the grayscale vision in Darkness and your Dim light still is brighter than regular Dim. I don't want Dim to be upgraded at all. Not having any sort of customization to your vision module is not exactly user friendly and your module still doesn't allow for certain lighting effects to look good because your Darkvision Dim Light is still brighter than the Dim light experienced by tokens without Darkvision.
