### ISSUE TITLE
Make Angles Matter

### ISSUE THREAD

**Issue by maxobremer** [dev7355608/vision-5e#95]
At the moment if you have a certain vision like bloodsense but your vision angle is reduced to lets say 10, you can still sense any creature with blood around you. It would be nice if you had the option to limit that to only detect things that are within your vision cone. 
Like let's say you have a spyglass of X detection, you might want to limit someone's vision depending on what you think they should see through that spyglass for example

**Comment by dev7355608** [comment]
I made the decision to only have Darkvision, Blindsight, Truesight, and Devil's Sight be affected by the Vision Angle, because with these you can actually see the cone of vision. If you don't have any of those 4 senses, you don't necessarily the vision cone without light, which makes it a bit confusing for the other detection modes if they where restricted by the vision angle.
