### ISSUE TITLE
Feature Request: Re-implement custom highlighting for Devils Sight

### ISSUE THREAD

**Issue by gambit07** [dev7355608/vision-5e#97]
One of the things I love about vision5e is the outline/highlighting for different vision modes. In v12, the highlighted outline for Devils Sight appears to no longer be working, making tokens difficult to see within Regions that use Darkness

**Comment by dev7355608** [comment]
I made the following change in 2.3.3. I don't think there should be a problem with visibility in normal darkness (otherwise it would even worse with darkvision), but I magical darkness (darkness sources) it is indeed very difficult to see the token without the outline.

> Tokens inside a darkness source detected by Devil's Sight and Truesight are now rendered with a outline filter.

https://github.com/dev7355608/vision-5e/releases/tag/v2.3.3

**Comment by gambit07** [comment]
Awesome, thank you!
