### ISSUE TITLE
"See invisibility" also sees ethereal while there is "see ethereal"

### ISSUE THREAD

**Issue by Weskernation** [dev7355608/vision-5e#99]
There is "See invisibility" and "Ethereal Sight"
"Ethereal Sight" sees Ethereal statussed actors but not invisibile -> Perfect
"See invisibility" sees Invisible AND Ethereal statussed actors which is not correct.

**Comment by dev7355608** [comment]
See Invisibility works like the See Invisibility spell, which allows sight into the Ethereal Plane.

The only See Invisibility-like official feat that doesn't allow sight into the Ethereal Plane is the The Third Eye (Wizard: School of Divination). At least that's the only one I know of. Because that's a pretty rare feat and the range quite small, I didn't make an effort to model the The Third Eye accurately.

I assume you have some a homebrew version of See invisibility that doesn't allow sight into the Ethereal Plane, or did I miss some See invisibility-like feat from official content that doesn't allow sight into the Ethereal Plane?

**Comment by Weskernation** [comment]
Aha, with the spell you are correct. I was not thinking about the spell. I look at it as a vision type on its own. With the spell I would have give the actor both vision types.
